<?php

$host = "localhost";
$dbUser = "root";
$password = "";
$database = "Armor";

// Create connection
$conn = new mysqli($host, $dbUser, $password, $database);
// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

//$sql = "INSERT INTO `Hands` (`id`, `name`, `img`, `layer`) VALUES ('12', 'qwweqr', 'qwer', '1')";

// List of armor piece names
$chest_pieces = [
    "Agdayne's Black Robes",
    "Alonne Captain Armor",
    "Alonne Knight Armor",
    "Alva Armor",
    "Archdrake Robes",
    "Astrologist Robe",
    "Aurous Armor",
    "Bandit Armor",
    "Bellkeeper Armor",
    "Benhart's Armor",
    "Black Dragon Armor",
    "Black Hollow Mage Robes",
    "Black Leather Armor",
    "Black Robes",
    "Black Witch Cloak",
    "Bone King Armor",
    "Brigand Armor",
    "Cale's Armor",
    "Catarina Armor",
    "Chaos Robe",
    "Creighton's Armor",
    "Dark Armor",
    "Desert Sorceress Top",
    "Dingy Robe",
    "Dragon Acolyte Armor",
    "Dragonrider Armor",
    "Drakekeeper Armor",
    "Drangleic Mail",
    "Elite Knight Armor",
    "Executioner Armor",
    "Falconer Armor",
    "Faraam Armor",
    "Grave Warden Armor",
    "Gyrm Armor",
    "Gyrm Warrior Armor",
    "Hard Leather Armor",
    "Havel's Armor",
    "Heide Knight Armor",
    "Hexer Chest",
    "Hollow Infantry Armor",
    "Hollow Soldier Armor",
    "Imperious Armor",
    "Imported Tunic",
    "Infantry Armor",
    "Insolent Armor",
    "Ironclad Armor",
    "Jester's Robe",
    "Judgement Robe",
    "King's Armor",
    "Knight's Armor",
    "Leydia Black Armor",
    "Leydia White Robe",
    "Lion Mage Robe",
    "Lion Warrior Cape",
    "Llewellyn Armor",
    "Looking Glass Armor",
    "Lucatiel's Armor",
    "Mad Warrior Armor",
    "Manikin Top",
    "Mastodon Armor",
    "Monastery Robe",
    "Moon Butterfly Pinions",
    "Nahr Alma Armor",
    "Old Ironclad Armor",
    "Old Knight Armor",
    "Pate's Armor",
    "Peasant Top",
    "Penal Straight Jacket",
    "Priestess Robe",
    "Prisoner's Rags",
    "Red Lion Warrior Cape",
    "Rogue Armor",
    "Royal Soldier Armor",
    "Royal Swordsman Armor",
    "Ruin Armor",
    "Rusted Mastodon Armor",
    "Saint's Robe",
    "Shadow Top",
    "Singer's Dress",
    "Smelter Demon Armor",
    "Steel Armor",
    "Syan's Armor",
    "Targray's Armor",
    "Tattered Cloth Robe",
    "Throne Defender Set",
    "Throne Watcher Armor",
    "Traveling Merchant Coat",
    "Tseldora Top",
    "Varangian Armor",
    "Velstadt's Armor",
    "Vengarl's Armor",
    "Wanderer Set",
    "White Hollow Top",
    "White Priest Headpiece",
    "Witch Robe",
    "Xanthous Overcoat"
];
$head_pieces = [
  "Alonne Captain Helm",
  "Alonne Knight Helm",
  "Alva Helm",
  "Archdrake Helm",
  "Astrologist's Hat",
  "Aurous Helm",
  "Bandit Helm",
  "Bell Keeper Helm",
  "Benhart's Knight Helm",
  "Black Hollow Mage Hood",
  "Black Hood",
  "Black Leather Thief Mask",
  "Black Witch Hat",
  "Bone King Crown",
  "Brigand Hood",
  "Cale's Helm",
  "Catarina Helm",
  "Chaos Hood",
  "Creighton's Helm",
  "Dark Mask",
  "Desert Sorceress Hood",
  "Dingy Hood",
  "Dragon Acolyte Helm",
  "Dragon Sage Hood",
  "Dragonrider Helm",
  "Drakeblood Helm",
  "Drakekeeper Helm",
  "Drangleic Helm",
  "Durgo's Hat",
  "Elite Knight Helm",
  "Executioner Helm",
  "Falconer Helm",
  "Faraam Helm",
  "Grave Warden Helm",
  "Gyrm Helm",
  "Gyrm Warrior Greathelm",
  "Gyrm Warrior Helm",
  "Hard Leather Helm",
  "Heide Knight Iron Mask",
  "Hexer Hood",
  "Hollow Infantry Helm",
  "Hollow Soldier Helm",
  "Hunter's Hat",
  "Imperious Helm",
  "Imported Hood",
  "Infantry Helm",
  "Insolent Helm",
  "Ironclad Helm",
  "Jester's Cap",
  "Judgement Helm",
  "King's Helm",
  "Knight Helm",
  "Leydia Black Hood",
  "Leydia White Hood",
  "Lion Warrior Helm",
  "Looking Glass Helm",
  "Lucatiel's Helm",
  "Mad Warrior Mask",
  "Manikin Mask",
  "Mastodon Helm",
  "Monastery Headcloth",
  "Monastery Hood",
  "Moon Butterfly Hat",
  "Nahr Alma Helm",
  "Old Ironclad Helm",
  "Old Knight Helm",
  "Pate's Helm",
  "Peasant's Hat",
  "Penal Mask",
  "Priestess Hood",
  "Prisoner's Hood",
  "Rogue Helm",
  "Royal Soldier Helm",
  "Royal Swordsman Helm",
  "Ruin Helm",
  "Rusted Mastodon Helm",
  "Saint's Hood",
  "Sanctum Knight Helm",
  "Shadow Mask",
  "Smelter Demon Helm",
  "Steel Helm",
  "Syan's Helm",
  "Targray's Helm",
  "Tattered Cloth Hood",
  "Throne Defender Helm",
  "Throne Watcher Helm",
  "Traveling Merchant Hat",
  "Tseldora Hat",
  "Varangian Helm",
  "Velstadt's Helm",
  "Vengarl's Helm",
  "Wanderer Hood",
  "White Hollow Helm",
  "White Priest Headpiece",
  "Worlock Mask",
  "Xanthous Crown"
];
$hand_pieces = [
    "Agdayne's Black Gloves",
    "Alonne Captain Gauntlets",
    "Alonne Knight Gauntlets",
    "Alva Gauntlets",
    "Archdrake Gloves",
    "Astrologist Gloves",
    "Aurous Gauntlets",
    "Bandit Gauntlets",
    "Bellkeeper Gauntlets",
    "Benhart's Gauntlets",
    "Black Dragon Gauntlets",
    "Black Leather Gauntlets",
    "Black Gloves",
    "Bone King Gauntlets",
    "Brigand Gauntlets",
    "Catarina Gauntlets",
    "Chaos Gloves",
    "Creighton's Gauntlets",
    "Dark Gauntlets",
    "Desert Sorceress Gauntlets",
    "Dingy Gloves",
    "Dragon Acolyte Gauntlets",
    "Dragonrider Gauntlets",
    "Drakekeeper Gauntlets",
    "Elite Knight Gauntlets",
    "Executioner Gauntlets",
    "Falconer Gauntlets",
    "Faraam Gauntlets",
    "Grave Warden Gauntlets",
    "Gyrm Gauntlets",
    "Gyrm Warrior Gauntlets",
    "Hard Leather Gauntlets",
    "Havel's Gauntlets",
    "Heide Knight Gauntlets",
    "Hollow Infantry Gauntlets",
    "Hollow Soldier Gauntlets",
    "Leather Gauntlets",
    "Imperious Gauntlets",
    "Infantry Gauntlets",
    "Insolent Gauntlets",
    "Ironclad Gauntlets",
    "Jester's Gloves",
    "Judgement Gloves",
    "King's Gauntlets",
    "Knight's Gauntlets",
    "Leydia Black Gauntlets",
    "Leydia White Gloves",
    "Lion Mage Cuffs",
    "Llewellyn Gauntlets",
    "Looking Glass Gauntlets",
    "Lucatiel's Gauntlets",
    "Mad Warrior Gauntlets",
    "Manikin Gauntlets",
    "Mastodon Gauntlets",
    "Monastery Gloves",
    "Moon Butterfly Pinions",
    "Nahr Alma Gauntlets",
    "Old Ironclad Gauntlets",
    "Old Knight Gauntlets",
    "Pate's Gauntlets",
    "Peasant Gauntlets",
    "Penal Straight Jacket",
    "Priestess Gloves",
    "Prisoner's Rags",
    "Rogue Gloves",
    "Royal Soldier Gauntlets",
    "Royal Swordsman Gauntlets",
    "Ruin Gauntlets",
    "Rusted Mastodon Gauntlets",
    "Saint's Gloves",
    "Shadow Gauntlets",
    "Smelter Demon Gauntlets",
    "Steel Gauntlets",
    "Syan's Gloves",
    "Targray's Gauntlets",
    "Tattered Cloth Gloves",
    "Throne Defender Set",
    "Throne Watcher Gauntlets",
    "Traveleing Merchant Coat",
    "Tseldora Gauntlets",
    "Varangian Gauntlets",
    "Velstadt's Gauntlets",
    "Vengarl's Gauntlets",
    "Wanderer Set",
    "White Priest Gloves",
    "Engraved Gauntlets"
  ];
$leggings_pieces = [
  "Agdayne's Black Kilt",
  "Alonne Captain Leggings",
  "Alonne Knight Leggings",
  "Alva Leggings",
  "Archdrake Leggings",
  "Astrologist Kilt",
  "Aurous Invisible Leggings",
  "Aurous Visible Leggings",
  "Bandit Leggings",
  "Bellkeeper Leggings",
  "Benhart's Boots",
  "Black Dragon Leggings",
  "Black Leather Boots",
  "Black Leggings",
  "Black Witch Kilt",
  "Blood Stained Skirt",
  "Bone King Kilt",
  "Brigand Trousers",
  "Cale's Leggings",
  "Catarina Leggings",
  "Chaos Leggings",
  "Creighton's Leggings",
  "Dark Leggings",
  "Desert Sorceress Skirt",
  "Dragon Acolyte Boot",
  "Dragonrider Leggings",
  "Drakekeeper Leggings",
  "Drangleic Leggings",
  "Elite Knight Leggings",
  "Executioner Leggings",
  "Falconer Boots",
  "Faraam Leggings",
  "Flying Feline Boots",
  "Grave Warden Leggings",
  "Gyrm Boots",
  "Gyrm Warrior Boots",
  "Hard Leather Leggings",
  "Havel's Leggings",
  "Heide Knight Leggings",
  "Hexer Leggings",
  "Hollow Infantry Boots",
  "Hollow Soldier Leggings",
  "Imperious Leggings",
  "Imported Trousers",
  "Infantry Leggings",
  "Insolent Boots",
  "Ironclad Leggings",
  "Jester's Boots",
  "Judgement Leggings",
  "King's Leggings",
  "Knight's Leggings",
  "Leather Leggings",
  "Lion Mage Skirt",
  "Lion Warrior Boots",
  "Llewellyn Leggings",
  "Looking Glass Leggings",
  "Lucatiel's Leggings",
  "Mad Warrior Leggings",
  "Manikin Leggings",
  "Mastodon Leggings",
  "Monastery Skirt",
  "Moon Butterfly Skirt",
  "Nahr Alma Leggings",
  "Old Ironclad Leggings",
  "Old Knight Leggings",
  "Pate's Leggings",
  "Peasant Leggings",
  "Penal Skirt",
  "Priestess Kilt",
  "Prisoner's Waistcloth",
  "Ruin Leggings",
  "Rusted Mastodon Leggings",
  "Saint's Leggings",
  "Shadow Leggings",
  "Smelter Demon Leggings",
  "Steel Leggings",
  "Syan's Leggings",
  "Targray's Leggings",
  "Throne Defender Leggings",
  "Throne Watcher Leggings",
  "Traveling Merchant Leggings",
  "Tseldora Leggings",
  "Varangian Leggings",
  "Velstadt's Leggings",
  "Vengarl's Leggings",
  "Wanderer Leggings",
  "White Priest Skirt",
  "Xanthous Kilt"
];


foreach ($head_pieces as $armor_id => $armor_name) {
    $armor_id += 1;
    $escaped_armor_name = $conn->real_escape_string($armor_name);
    // Construct the SQL query
    $sql = "INSERT INTO `Head` (`id`, `name`, `Img`, `layer`) VALUES ($armor_id, '$escaped_armor_name', '', 5)";
    if ($conn->query($sql) === TRUE) {
        echo "New record created successfully";
      } else {
        echo "Error: " . $sql . "<br>" . $conn->error;
      }
}
?> 