<?php
require_once('config.php');

// Function to insert data into a specified table
function insertData($dbConn, $table, $items, $layer) {
    foreach ($items as $index => $item) {
        // Sanitize and prepare data
        $name = mysqli_real_escape_string($dbConn, $item['name']);
        $img = mysqli_real_escape_string($dbConn, $item['img']);
        $id = $index + 1; // Assuming IDs start at 1 and increment

        // Prepare SQL query
        $qry = "INSERT INTO $table (id, name, img, layer) VALUES ($id, '$name', '$img', $layer)";
        
        // Execute query
        if (!$dbConn->query($qry)) {
            echo "Error: " . $dbConn->error . "\n";
        }
    }
}

// Define item data
$headItems = [
    ['name' => 'Alonne Captain Helm', 'img' => 'img/alonne_captain_helm.png'],
    ['name' => 'Alonne Knight Helm', 'img' => 'img/alonne_knight_helm.png'],
    ['name' => 'Alonne`s Helm', 'img' => 'img/alonnes_helm.png'],
    ['name' => 'Alva Helm', 'img' => 'img/alva_helm.png'],
    ['name' => 'Archdrake Helm', 'img' => 'img/archdrake_helm.png'],
    ['name' => 'Bell Keeper Helmet', 'img' => 'img/bell_keeper_helmet.png'],
    ['name' => 'Benhart`s Knight Helm', 'img' => 'img/benharts_knight_helm.png'],
    ['name' => 'Black Dragon Helm', 'img' => 'img/black_dragon_helm.png'],
    ['name' => 'Black Hollow Mage Hood', 'img' => 'img/black_hollow_mage_hood.png'],
    ['name' => 'Black Hood', 'img' => 'img/black_hood.png'],
    ['name' => 'Black Witch Domino Mask', 'img' => 'img/black_witch_domino_mask.png'],
    ['name' => 'Black Witch Hat', 'img' => 'img/black_witch_hat.png'],
    ['name' => 'Black Witch Veil', 'img' => 'img/black_witch_veil.png'],
    ['name' => 'Bone Crown', 'img' => 'img/bone_crown.png'],
    ['name' => 'Brigand Hood', 'img' => 'img/brigand_hood.png'],
    ['name' => 'Cale`s Helm', 'img' => 'img/cales_helm.png'],
    ['name' => 'Catarina Helm', 'img' => 'img/catarina_helm.png'],
    ['name' => 'Chaos Hood', 'img' => 'img/chaos_hood.png'],
    ['name' => 'Charred Loyce Helm', 'img' => 'img/charred_loyce_helm.png'],
    ['name' => 'Creighton`s Steel Mask', 'img' => 'img/creightons_steel_mask.png'],
    ['name' => 'Crown of the Ivory King', 'img' => 'img/crown_of_the_ivory_king.png'],
    ['name' => 'Crown of the Old Iron King', 'img' => 'img/crown_of_the_old_iron_king.png'],
    ['name' => 'Crown of the Sunken King', 'img' => 'img/crown_of_the_sunken_king.png'],
    ['name' => 'Dark Mask', 'img' => 'img/dark_mask.png'],
    ['name' => 'Desert Sorceress Hood', 'img' => 'img/desert_sorceress_hood.png'],
    ['name' => 'Dingy Hood', 'img' => 'img/dingy_hood.png'],
    ['name' => 'Dragon Acolyte Mask', 'img' => 'img/dragon_acolyte_mask.png'],
    ['name' => 'Dragon Sage Hood', 'img' => 'img/dragon_sage_hood.png'],
    ['name' => 'Dragonrider Helm', 'img' => 'img/dragonrider_helm.png'],
    ['name' => 'Drakeblood Helm', 'img' => 'img/drakeblood_helm.png'],
    ['name' => 'Drakekeeper Helm', 'img' => 'img/drakekeeper_helm.png'],
    ['name' => 'Drangleic Helm', 'img' => 'img/drangleic_helm.png'],
    ['name' => 'Durgo`s Hat', 'img' => 'img/durgos_hat.png'],
    ['name' => 'Elite Knight Helm', 'img' => 'img/elite_knight_helm.png'],
    ['name' => 'Executioner Helm', 'img' => 'img/executioner_helm.png'],
    ['name' => 'Falconer Helm', 'img' => 'img/falconer_helm.png'],
    ['name' => 'Faraam Helm', 'img' => 'img/faraam_helm.png'],
    ['name' => 'Fume Sorcerer Mask', 'img' => 'img/fume_sorcerer_mask.png'],
    ['name' => 'Grave Warden Mask', 'img' => 'img/grave_warden_mask.png'],
    ['name' => 'Gyrm Helm', 'img' => 'img/gyrm_helm.png'],
    ['name' => 'Gyrm Warrior Greathelm', 'img' => 'img/gyrm_warrior_greathelm.png'],
    ['name' => 'Gyrm Warrior Helm', 'img' => 'img/gyrm_warrior_helm.png'],
    ['name' => 'Havel`s Helm', 'img' => 'img/havels_helm.png'],
    ['name' => 'Heide Knight Greathelm', 'img' => 'img/heide_knight_greathelm.png'],
    ['name' => 'Heide Knight Iron Mask', 'img' => 'img/heide_knight_iron_mask.png'],
    ['name' => 'Helm of Aurous', 'img' => 'img/helm_of_aurous.png'],
    ['name' => 'Helm of Aurous (T)', 'img' => 'img/helm_of_aurous_t.png'],
    ['name' => 'Hexer`s Hood', 'img' => 'img/hexers_hood.png'],
    ['name' => 'Hollow Infantry Helm', 'img' => 'img/hollow_infantry_helm.png'],
    ['name' => 'Hollow Skin', 'img' => 'img/hollow_skin.png'],
    ['name' => 'Hollow Soldier Helm', 'img' => 'img/hollow_soldier_helm.png'],
    ['name' => 'Hood of the Forlorn', 'img' => 'img/hood_of_the_forlorn.png'],
    ['name' => 'Hunter`s Hat', 'img' => 'img/hunters_hat.png'],
    ['name' => 'Imperious Helm', 'img' => 'img/imperious_helm.png'],
    ['name' => 'Imported Hood', 'img' => 'img/imported_hood.png'],
    ['name' => 'Infantry Helm', 'img' => 'img/infantry_helm.png'],
    ['name' => 'Insolent Helm', 'img' => 'img/insolent_helm.png'],
    ['name' => 'Ironclad Helm', 'img' => 'img/ironclad_helm.png'],
    ['name' => 'Ivory King Helm', 'img' => 'img/ivory_king_helm.png'],
    ['name' => 'Jester`s Cap', 'img' => 'img/jesters_cap.png'],
    ['name' => 'King`s Crown', 'img' => 'img/kings_crown.png'],
    ['name' => 'Knight Helm', 'img' => 'img/knight_helm.png'],
    ['name' => 'Leydia Black Hood', 'img' => 'img/leydia_black_hood.png'],
    ['name' => 'Leydia White Hood', 'img' => 'img/leydia_white_hood.png'],
    ['name' => 'Lion Warrior Helm', 'img' => 'img/lion_warrior_helm.png'],
    ['name' => 'Looking Glass Mask', 'img' => 'img/looking_glass_mask.png'],
    ['name' => 'Loyce Helm', 'img' => 'img/loyce_helm.png'],
    ['name' => 'Lucatiel`s Mask', 'img' => 'img/lucatiels_mask.png'],
    ['name' => 'Mad Warrior Mask', 'img' => 'img/mad_warrior_mask.png'],
    ['name' => 'Manikin Mask', 'img' => 'img/manikin_mask.png'],
    ['name' => 'Mask of Judgment', 'img' => 'img/mask_of_judgment.png'],
    ['name' => 'Mastodon Helm', 'img' => 'img/mastodon_helm.png'],
    ['name' => 'Minotaur Helm', 'img' => 'img/minotaur_helm.png'],
    ['name' => 'Mirrah Greathelm', 'img' => 'img/mirrah_greathelm.png'],
    ['name' => 'Monastery Headcloth', 'img' => 'img/monastery_headcloth.png'],
    ['name' => 'Moon Butterfly Hat', 'img' => 'img/moon_butterfly_hat.png'],
    ['name' => 'Nahr Alma Hood', 'img' => 'img/nahr_alma_hood.png'],
    ['name' => 'Necromancer Hood', 'img' => 'img/necromancer_hood.png'],
    ['name' => 'Old Bell Helm', 'img' => 'img/old_bell_helm.png'],
    ['name' => 'Old Knight Helm', 'img' => 'img/old_knight_helm.png'],
    ['name' => 'Old Mirrah Visor', 'img' => 'img/old_mirrah_visor.png'],
    ['name' => 'Old Soldier Helm', 'img' => 'img/old_soldier_helm.png'],
    ['name' => 'Old Sun Helm', 'img' => 'img/old_sun_helm.png'],
    ['name' => 'Old Ironclad Helm', 'img' => 'img/old_ironclad_helm.png'],
    ['name' => 'Old Iron King Crown', 'img' => 'img/old_iron_king_crown.png'],
    ['name' => 'Old Knight Helm', 'img' => 'img/old_knight_helm.png'],
    ['name' => 'Peasant Hat', 'img' => 'img/peasant_hat.png'],
    ['name' => 'Penal Mask', 'img' => 'img/penal_mask.png'],
    ['name' => 'Prowler Hood', 'img' => 'img/prowler_hood.png'],
    ['name' => 'Rogue Hood', 'img' => 'img/rogue_hood.png'],
    ['name' => 'Royal Swordsman Helm', 'img' => 'img/royal_swordsman_helm.png'],
    ['name' => 'Saint`s Hood', 'img' => 'img/saints_hood.png'],
    ['name' => 'Sanctum Knight Helm', 'img' => 'img/sanctum_knight_helm.png'],
    ['name' => 'Sanctum Priestess Tiara', 'img' => 'img/sanctum_priestess_tiara.png'],
    ['name' => 'Shadow Mask', 'img' => 'img/shadow_mask.png'],
    ['name' => 'Shiva`s Helm', 'img' => 'img/shivas_helm.png'],
    ['name' => 'Solider`s Helm', 'img' => 'img/soldiers_helm.png'],
    ['name' => 'Steel Helm', 'img' => 'img/steel_helm.png'],
    ['name' => 'Targray`s Helm', 'img' => 'img/targrays_helm.png'],
    ['name' => 'Tattered Cloth Hood', 'img' => 'img/tattered_cloth_hood.png'],
    ['name' => 'Throne Watcher Helm', 'img' => 'img/throne_watcher_helm.png'],
    ['name' => 'Throne Defender Helm', 'img' => 'img/throne_defender_helm.png'],
    ['name' => 'Varangian Helm', 'img' => 'img/varangian_helm.png'],
    ['name' => 'Velstadt`s Helm', 'img' => 'img/velstadts_helm.png'],
    ['name' => 'Vengarl`s Helm', 'img' => 'img/vengarls_helm.png'],
    ['name' => 'White Hollow Mage Hood', 'img' => 'img/white_hollow_mage_hood.png'],
    ['name' => 'White Priest Chapeau', 'img' => 'img/white_priest_chapeau.png'],
    ['name' => 'White Wizard Hat', 'img' => 'img/white_wizard_hat.png'],
    ['name' => 'Witchtree Branch', 'img' => 'img/witchtree_branch.png'],
    ['name' => 'Xanthous Crown', 'img' => 'img/xanthous_crown.png']
];

$chestItems = [
    ['name' => 'Agdayne`s Black Robe', 'img' => 'img/agdayne_black_robe.png'],
    ['name' => 'Alonne Captain Armor', 'img' => 'img/alonne_captain_armor.png'],
    ['name' => 'Alonne Knight Armor', 'img' => 'img/alonne_knight_armor.png'],
    ['name' => 'Alonne`s Armor', 'img' => 'img/alonnes_armor.png'],
    ['name' => 'Archdrake Robes', 'img' => 'img/archdrake_robes.png'],
    ['name' => 'Astrologist`s Robe', 'img' => 'img/astrologists_robe.png'],
    ['name' => 'Aurous Armor', 'img' => 'img/aurous_armor.png'],
    ['name' => 'Aurous Armor (Transparent)', 'img' => 'img/aurous_armor_transparent.png'],
    ['name' => 'Bandit Armor', 'img' => 'img/bandit_armor.png'],
    ['name' => 'Bell Keeper Armor', 'img' => 'img/bell_keeper_armor.png'],
    ['name' => 'Benhart`s Armor', 'img' => 'img/benharts_armor.png'],
    ['name' => 'Black Dragon Armor', 'img' => 'img/black_dragon_armor.png'],
    ['name' => 'Black Hollow Mage Robe', 'img' => 'img/black_hollow_mage_robe.png'],
    ['name' => 'Black Robe', 'img' => 'img/black_robe.png'],
    ['name' => 'Black Witch Robe', 'img' => 'img/black_witch_robe.png'],
    ['name' => 'Bone Armor', 'img' => 'img/bone_armor.png'],
    ['name' => 'Brigand Armor', 'img' => 'img/brigand_armor.png'],
    ['name' => 'Cale`s Armor', 'img' => 'img/cales_armor.png'],
    ['name' => 'Catarina Armor', 'img' => 'img/catarina_armor.png'],
    ['name' => 'Chaos Robes', 'img' => 'img/chaos_robes.png'],
    ['name' => 'Charred Loyce Armor', 'img' => 'img/charred_loyce_armor.png'],
    ['name' => 'Creighton`s Chainmail', 'img' => 'img/creightons_chainmail.png'],
    ['name' => 'Dark Armor', 'img' => 'img/dark_armor.png'],
    ['name' => 'Desert Sorceress Robe', 'img' => 'img/desert_sorceress_robe.png'],
    ['name' => 'Dingy Robe', 'img' => 'img/dingy_robe.png'],
    ['name' => 'Dragon Acolyte Robe', 'img' => 'img/dragon_acolyte_robe.png'],
    ['name' => 'Dragon Sage Robe', 'img' => 'img/dragon_sage_robe.png'],
    ['name' => 'Dragonrider Armor', 'img' => 'img/dragonrider_armor.png'],
    ['name' => 'Drakeblood Armor', 'img' => 'img/drakeblood_armor.png'],
    ['name' => 'Drakekeeper Armor', 'img' => 'img/drakekeeper_armor.png'],
    ['name' => 'Drangleic Mail', 'img' => 'img/drangleic_mail.png'],
    ['name' => 'Durgo`s Armor', 'img' => 'img/durgos_armor.png'],
    ['name' => 'Elite Knight Armor', 'img' => 'img/elite_knight_armor.png'],
    ['name' => 'Executioner Armor', 'img' => 'img/executioner_armor.png'],
    ['name' => 'Falconer Armor', 'img' => 'img/falconer_armor.png'],
    ['name' => 'Faraam Armor', 'img' => 'img/faraam_armor.png'],
    ['name' => 'Fume Sorcerer Robes', 'img' => 'img/fume_sorcerer_robes.png'],
    ['name' => 'Grave Warden Robe', 'img' => 'img/grave_warden_robe.png'],
    ['name' => 'Gyrm Armor', 'img' => 'img/gyrm_armor.png'],
    ['name' => 'Gyrm Warrior Armor', 'img' => 'img/gyrm_warrior_armor.png'],
    ['name' => 'Havel`s Armor', 'img' => 'img/havels_armor.png'],
    ['name' => 'Heide Knight Chainmail', 'img' => 'img/heide_knight_chainmail.png'],
    ['name' => 'Helm of Aurous Armor', 'img' => 'img/helm_of_aurous_armor.png'],
    ['name' => 'Helm of Aurous Armor (T)', 'img' => 'img/helm_of_aurous_armor_t.png'],
    ['name' => 'Hexer`s Robes', 'img' => 'img/hexers_robes.png'],
    ['name' => 'Hollow Infantry Armor', 'img' => 'img/hollow_infantry_armor.png'],
    ['name' => 'Hollow Soldier Armor', 'img' => 'img/hollow_soldier_armor.png'],
    ['name' => 'Hood of the Forlorn Armor', 'img' => 'img/hood_of_the_forlorn_armor.png'],
    ['name' => 'Hunter`s Armor', 'img' => 'img/hunters_armor.png'],
    ['name' => 'Imperious Armor', 'img' => 'img/imperious_armor.png'],
    ['name' => 'Imported Hood Armor', 'img' => 'img/imported_hood_armor.png'],
    ['name' => 'Infantry Armor', 'img' => 'img/infantry_armor.png'],
    ['name' => 'Insolent Armor', 'img' => 'img/insolent_armor.png'],
    ['name' => 'Ironclad Armor', 'img' => 'img/ironclad_armor.png'],
    ['name' => 'Ivory King Armor', 'img' => 'img/ivory_king_armor.png'],
    ['name' => 'Jester`s Robes', 'img' => 'img/jesters_robes.png'],
    ['name' => 'Knight Armor', 'img' => 'img/knight_armor.png'],
    ['name' => 'Leydia Black Robe', 'img' => 'img/leydia_black_robe.png'],
    ['name' => 'Leydia White Robe', 'img' => 'img/leydia_white_robe.png'],
    ['name' => 'Lion Warrior Armor', 'img' => 'img/lion_warrior_armor.png'],
    ['name' => 'Looking Glass Armor', 'img' => 'img/looking_glass_armor.png'],
    ['name' => 'Loyce Armor', 'img' => 'img/loyce_armor.png'],
    ['name' => 'Lucatiel`s Armor', 'img' => 'img/lucatiels_armor.png'],
    ['name' => 'Mad Warrior Armor', 'img' => 'img/mad_warrior_armor.png'],
    ['name' => 'Manikin Armor', 'img' => 'img/manikin_armor.png'],
    ['name' => 'Mask of Judgment Armor', 'img' => 'img/mask_of_judgment_armor.png'],
    ['name' => 'Mastodon Armor', 'img' => 'img/mastodon_armor.png'],
    ['name' => 'Minotaur Armor', 'img' => 'img/minotaur_armor.png'],
    ['name' => 'Mirrah Armor', 'img' => 'img/mirrah_armor.png'],
    ['name' => 'Monastery Longshirt', 'img' => 'img/monastery_longshirt.png'],
    ['name' => 'Moon Butterfly Wings', 'img' => 'img/moon_butterfly_wings.png'],
    ['name' => 'Nahr Alma Robes', 'img' => 'img/nahr_alma_robes.png'],
    ['name' => 'Necromancer Robes', 'img' => 'img/necromancer_robes.png'],
    ['name' => 'Old Bell Armor', 'img' => 'img/old_bell_armor.png'],
    ['name' => 'Old Knight Armor', 'img' => 'img/old_knight_armor.png'],
    ['name' => 'Old Mirrah Vest', 'img' => 'img/old_mirrah_vest.png'],
    ['name' => 'Old Soldier Armor', 'img' => 'img/old_soldier_armor.png'],
    ['name' => 'Old Sun Robes', 'img' => 'img/old_sun_robes.png'],
    ['name' => 'Old Ironclad Armor', 'img' => 'img/old_ironclad_armor.png'],
    ['name' => 'Peasant Attire', 'img' => 'img/peasant_attire.png'],
    ['name' => 'Penal Armor', 'img' => 'img/penal_armor.png'],
    ['name' => 'Prowler Armor', 'img' => 'img/prowler_armor.png'],
    ['name' => 'Rogue Armor', 'img' => 'img/rogue_armor.png'],
    ['name' => 'Royal Swordsman Armor', 'img' => 'img/royal_swordsman_armor.png'],
    ['name' => 'Saint`s Robes', 'img' => 'img/saints_robes.png'],
    ['name' => 'Sanctum Knight Armor', 'img' => 'img/sanctum_knight_armor.png'],
    ['name' => 'Sanctum Priestess Dress', 'img' => 'img/sanctum_priestess_dress.png'],
    ['name' => 'Shadow Garb', 'img' => 'img/shadow_garb.png'],
    ['name' => 'Shiva`s Armor', 'img' => 'img/shivas_armor.png'],
    ['name' => 'Soldier`s Armor', 'img' => 'img/soldiers_armor.png'],
    ['name' => 'Steel Armor', 'img' => 'img/steel_armor.png'],
    ['name' => 'Targray`s Armor', 'img' => 'img/targrays_armor.png'],
    ['name' => 'Tattered Cloth Armor', 'img' => 'img/tattered_cloth_armor.png'],
    ['name' => 'Throne Watcher Armor', 'img' => 'img/throne_watcher_armor.png'],
    ['name' => 'Throne Defender Armor', 'img' => 'img/throne_defender_armor.png'],
    ['name' => 'Varangian Armor', 'img' => 'img/varangian_armor.png'],
    ['name' => 'Velstadt`s Armor', 'img' => 'img/velstadts_armor.png'],
    ['name' => 'Vengarl`s Armor', 'img' => 'img/vengarls_armor.png'],
    ['name' => 'White Hollow Mage Robe', 'img' => 'img/white_hollow_mage_robe.png'],
    ['name' => 'White Priest Dress', 'img' => 'img/white_priest_dress.png'],
    ['name' => 'White Wizard Robe', 'img' => 'img/white_wizard_robe.png'],
    ['name' => 'Witchtree Branch Armor', 'img' => 'img/witchtree_branch_armor.png'],
    ['name' => 'Xanthous Overcoat', 'img' => 'img/xanthous_overcoat.png']
];

$handsItems = [
    ['name' => 'Agdayne`s Black Gloves', 'img' => 'img/agdayne_black_gloves.png'],
    ['name' => 'Alonne Captain Gauntlets', 'img' => 'img/alonne_captain_gauntlets.png'],
    ['name' => 'Alonne Knight Gauntlets', 'img' => 'img/alonne_knight_gauntlets.png'],
    ['name' => 'Alonne`s Gauntlets', 'img' => 'img/alonnes_gauntlets.png'],
    ['name' => 'Archdrake Gloves', 'img' => 'img/archdrake_gloves.png'],
    ['name' => 'Astrologist`s Gauntlets', 'img' => 'img/astrologists_gauntlets.png'],
    ['name' => 'Aurous Gauntlets', 'img' => 'img/aurous_gauntlets.png'],
    ['name' => 'Bandit Gauntlets', 'img' => 'img/bandit_gauntlets.png'],
    ['name' => 'Bell Keeper Gloves', 'img' => 'img/bell_keeper_gloves.png'],
    ['name' => 'Benhart`s Gauntlets', 'img' => 'img/benharts_gauntlets.png'],
    ['name' => 'Black Dragon Gauntlets', 'img' => 'img/black_dragon_gauntlets.png'],
    ['name' => 'Black Hollow Mage Gloves', 'img' => 'img/black_hollow_mage_gloves.png'],
    ['name' => 'Black Witch Wrappings', 'img' => 'img/black_witch_wrappings.png'],
    ['name' => 'Bone King Gauntlets', 'img' => 'img/bone_king_gauntlets.png'],
    ['name' => 'Brigand Gauntlets', 'img' => 'img/brigand_gauntlets.png'],
    ['name' => 'Cale`s Gauntlets', 'img' => 'img/cales_gauntlets.png'],
    ['name' => 'Catarina Gauntlets', 'img' => 'img/catarina_gauntlets.png'],
    ['name' => 'Charred Loyce Gauntlets', 'img' => 'img/charred_loyce_gauntlets.png'],
    ['name' => 'Creighton`s Chain Gloves', 'img' => 'img/creightons_chain_gloves.png'],
    ['name' => 'Dark Gauntlets', 'img' => 'img/dark_gauntlets.png'],
    ['name' => 'Desert Sorceress Gloves', 'img' => 'img/desert_sorceress_gloves.png'],
    ['name' => 'Dragon Acolyte Gloves', 'img' => 'img/dragon_acolyte_gloves.png'],
    ['name' => 'Dragon Sage Gloves', 'img' => 'img/dragon_sage_gloves.png'],
    ['name' => 'Dragonrider Gauntlets', 'img' => 'img/dragonrider_gauntlets.png'],
    ['name' => 'Drakeblood Gauntlets', 'img' => 'img/drakeblood_gauntlets.png'],
    ['name' => 'Drakekeeper Gauntlets', 'img' => 'img/drakekeeper_gauntlets.png'],
    ['name' => 'Drangleic Gauntlets', 'img' => 'img/drangleic_gauntlets.png'],
    ['name' => 'Durgo`s Gauntlets', 'img' => 'img/durgos_gauntlets.png'],
    ['name' => 'Elite Knight Gauntlets', 'img' => 'img/elite_knight_gauntlets.png'],
    ['name' => 'Executioner Gauntlets', 'img' => 'img/executioner_gauntlets.png'],
    ['name' => 'Falconer Gauntlets', 'img' => 'img/falconer_gauntlets.png'],
    ['name' => 'Faraam Gauntlets', 'img' => 'img/faraam_gauntlets.png'],
    ['name' => 'Fume Sorcerer Gloves', 'img' => 'img/fume_sorcerer_gloves.png'],
    ['name' => 'Grave Warden Cuffs', 'img' => 'img/grave_warden_cuffs.png'],
    ['name' => 'Gyrm Gauntlets', 'img' => 'img/gyrm_gauntlets.png'],
    ['name' => 'Gyrm Warrior Gauntlets', 'img' => 'img/gyrm_warrior_gauntlets.png'],
    ['name' => 'Havel`s Gauntlets', 'img' => 'img/havels_gauntlets.png'],
    ['name' => 'Heide Knight Gauntlets', 'img' => 'img/heide_knight_gauntlets.png'],
    ['name' => 'Hexer`s Gloves', 'img' => 'img/hexers_gloves.png'],
    ['name' => 'Hollow Infantry Gloves', 'img' => 'img/hollow_infantry_gloves.png'],
    ['name' => 'Hollow Soldier Gauntlets', 'img' => 'img/hollow_soldier_gauntlets.png'],
    ['name' => 'Hunter`s Gauntlets', 'img' => 'img/hunters_gauntlets.png'],
    ['name' => 'Imperious Gauntlets', 'img' => 'img/imperious_gauntlets.png'],
    ['name' => 'Imported Gauntlets', 'img' => 'img/imported_gauntlets.png'],
    ['name' => 'Infantry Gloves', 'img' => 'img/infantry_gloves.png'],
    ['name' => 'Insolent Gauntlets', 'img' => 'img/insolent_gauntlets.png'],
    ['name' => 'Ironclad Gauntlets', 'img' => 'img/ironclad_gauntlets.png'],
    ['name' => 'Ivory King Gauntlets', 'img' => 'img/ivory_king_gauntlets.png'],
    ['name' => 'Jester`s Gloves', 'img' => 'img/jesters_gloves.png'],
    ['name' => 'Knight Gauntlets', 'img' => 'img/knight_gauntlets.png'],
    ['name' => 'Leydia Black Gloves', 'img' => 'img/leydia_black_gloves.png'],
    ['name' => 'Leydia White Gloves', 'img' => 'img/leydia_white_gloves.png'],
    ['name' => 'Lion Warrior Gauntlets', 'img' => 'img/lion_warrior_gauntlets.png'],
    ['name' => 'Looking Glass Gauntlets', 'img' => 'img/looking_glass_gauntlets.png'],
    ['name' => 'Loyce Gauntlets', 'img' => 'img/loyce_gauntlets.png'],
    ['name' => 'Lucatiel`s Gauntlets', 'img' => 'img/lucatiels_gauntlets.png'],
    ['name' => 'Mad Warrior Gauntlets', 'img' => 'img/mad_warrior_gauntlets.png'],
    ['name' => 'Manikin Gloves', 'img' => 'img/manikin_gloves.png'],
    ['name' => 'Mastodon Gauntlets', 'img' => 'img/mastodon_gauntlets.png'],
    ['name' => 'Minotaur Gauntlets', 'img' => 'img/minotaur_gauntlets.png'],
    ['name' => 'Mirrah Gloves', 'img' => 'img/mirrah_gloves.png'],
    ['name' => 'Moon Butterfly Cuffs', 'img' => 'img/moon_butterfly_cuffs.png'],
    ['name' => 'Nahr Alma Gauntlets', 'img' => 'img/nahr_alma_gauntlets.png'],
    ['name' => 'Necromancer Gloves', 'img' => 'img/necromancer_gloves.png'],
    ['name' => 'Old Bell Gauntlets', 'img' => 'img/old_bell_gauntlets.png'],
    ['name' => 'Old Knight Gauntlets', 'img' => 'img/old_knight_gauntlets.png'],
    ['name' => 'Old Mirrah Gloves', 'img' => 'img/old_mirrah_gloves.png'],
    ['name' => 'Old Soldier Gauntlets', 'img' => 'img/old_soldier_gauntlets.png'],
    ['name' => 'Old Sun Gloves', 'img' => 'img/old_sun_gloves.png'],
    ['name' => 'Old Ironclad Gauntlets', 'img' => 'img/old_ironclad_gauntlets.png'],
    ['name' => 'Peasant Long Gloves', 'img' => 'img/peasant_long_gloves.png'],
    ['name' => 'Penal Gloves', 'img' => 'img/penal_gloves.png'],
    ['name' => 'Prowler Gloves', 'img' => 'img/prowler_gloves.png'],
    ['name' => 'Rogue Gauntlets', 'img' => 'img/rogue_gauntlets.png'],
    ['name' => 'Royal Swordsman Gloves', 'img' => 'img/royal_swordsman_gloves.png'],
    ['name' => 'Saint`s Gloves', 'img' => 'img/saints_gloves.png'],
    ['name' => 'Sanctum Knight Gauntlets', 'img' => 'img/sanctum_knight_gauntlets.png'],
    ['name' => 'Sanctum Priestess Gloves', 'img' => 'img/sanctum_priestess_gloves.png'],
    ['name' => 'Shadow Gauntlets', 'img' => 'img/shadow_gauntlets.png'],
    ['name' => 'Shiva`s Gauntlets', 'img' => 'img/shivas_gauntlets.png'],
    ['name' => 'Soldier`s Gauntlets', 'img' => 'img/soldiers_gauntlets.png'],
    ['name' => 'Steel Gauntlets', 'img' => 'img/steel_gauntlets.png'],
    ['name' => 'Targray`s Gauntlets', 'img' => 'img/targrays_gauntlets.png'],
    ['name' => 'Tattered Cloth Gloves', 'img' => 'img/tattered_cloth_gloves.png'],
    ['name' => 'Throne Watcher Gauntlets', 'img' => 'img/throne_watcher_gauntlets.png'],
    ['name' => 'Throne Defender Gauntlets', 'img' => 'img/throne_defender_gauntlets.png'],
    ['name' => 'Varangian Gauntlets', 'img' => 'img/varangian_gauntlets.png'],
    ['name' => 'Velstadt`s Gauntlets', 'img' => 'img/velstadts_gauntlets.png'],
    ['name' => 'Vengarl`s Gauntlets', 'img' => 'img/vengarls_gauntlets.png'],
    ['name' => 'White Hollow Mage Gloves', 'img' => 'img/white_hollow_mage_gloves.png'],
    ['name' => 'White Priest Gloves', 'img' => 'img/white_priest_gloves.png'],
    ['name' => 'White Wizard Gloves', 'img' => 'img/white_wizard_gloves.png'],
    ['name' => 'Witchtree Branch Gloves', 'img' => 'img/witchtree_branch_gloves.png'],
    ['name' => 'Xanthous Gloves', 'img' => 'img/xanthous_gloves.png']
];

$legsItems = [
    ['name' => 'Agdayne`s Black Boots', 'img' => 'img/agdayne_black_boots.png'],
    ['name' => 'Alonne Captain Leggings', 'img' => 'img/alonne_captain_leggings.png'],
    ['name' => 'Alonne Knight Leggings', 'img' => 'img/alonne_knight_leggings.png'],
    ['name' => 'Alonne`s Leggings', 'img' => 'img/alonnes_leggings.png'],
    ['name' => 'Archdrake Boots', 'img' => 'img/archdrake_boots.png'],
    ['name' => 'Astrologist`s Bottoms', 'img' => 'img/astrologists_bottoms.png'],
    ['name' => 'Aurous Leggings', 'img' => 'img/aurous_leggings.png'],
    ['name' => 'Bandit Boots', 'img' => 'img/bandit_boots.png'],
    ['name' => 'Bell Keeper Trousers', 'img' => 'img/bell_keeper_trousers.png'],
    ['name' => 'Benhart`s Boots', 'img' => 'img/benharts_boots.png'],
    ['name' => 'Black Dragon Leggings', 'img' => 'img/black_dragon_leggings.png'],
    ['name' => 'Black Hollow Mage Boots', 'img' => 'img/black_hollow_mage_boots.png'],
    ['name' => 'Black Leather Boots', 'img' => 'img/black_leather_boots.png'],
    ['name' => 'Black Witch Trousers', 'img' => 'img/black_witch_trousers.png'],
    ['name' => 'Bone King Skirt', 'img' => 'img/bone_king_skirt.png'],
    ['name' => 'Brigand Trousers', 'img' => 'img/brigand_trousers.png'],
    ['name' => 'Cale`s Shoes', 'img' => 'img/cales_shoes.png'],
    ['name' => 'Catarina Leggings', 'img' => 'img/catarina_leggings.png'],
    ['name' => 'Charred Loyce Leggings', 'img' => 'img/charred_loyce_leggings.png'],
    ['name' => 'Creighton`s Chain Leggings', 'img' => 'img/creightons_chain_leggings.png'],
    ['name' => 'Dark Leggings', 'img' => 'img/dark_leggings.png'],
    ['name' => 'Desert Sorceress Skirt', 'img' => 'img/desert_sorceress_skirt.png'],
    ['name' => 'Dragon Acolyte Boots', 'img' => 'img/dragon_acolyte_boots.png'],
    ['name' => 'Dragon Sage Boots', 'img' => 'img/dragon_sage_boots.png'],
    ['name' => 'Dragonrider Leggings', 'img' => 'img/dragonrider_leggings.png'],
    ['name' => 'Drakeblood Leggings', 'img' => 'img/drakeblood_leggings.png'],
    ['name' => 'Drakekeeper Leggings', 'img' => 'img/drakekeeper_leggings.png'],
    ['name' => 'Drangleic Leggings', 'img' => 'img/drangleic_leggings.png'],
    ['name' => 'Durgo`s Trousers', 'img' => 'img/durgos_trousers.png'],
    ['name' => 'Elite Knight Leggings', 'img' => 'img/elite_knight_leggings.png'],
    ['name' => 'Executioner Leggings', 'img' => 'img/executioner_leggings.png'],
    ['name' => 'Falconer Boots', 'img' => 'img/falconer_boots.png'],
    ['name' => 'Faraam Boots', 'img' => 'img/faraam_boots.png'],
    ['name' => 'Fume Sorcerer Boots', 'img' => 'img/fume_sorcerer_boots.png'],
    ['name' => 'Grave Warden Bottoms', 'img' => 'img/grave_warden_bottoms.png'],
    ['name' => 'Gyrm Boots', 'img' => 'img/gyrm_boots.png'],
    ['name' => 'Gyrm Warrior Boots', 'img' => 'img/gyrm_warrior_boots.png'],
    ['name' => 'Havel`s Leggings', 'img' => 'img/havels_leggings.png'],
    ['name' => 'Heide Knight Leggings', 'img' => 'img/heide_knight_leggings.png'],
    ['name' => 'Hexer`s Boots', 'img' => 'img/hexers_boots.png'],
    ['name' => 'Hollow Infantry Boots', 'img' => 'img/hollow_infantry_boots.png'],
    ['name' => 'Hollow Soldier Leggings', 'img' => 'img/hollow_soldier_leggings.png'],
    ['name' => 'Hunter`s Boots', 'img' => 'img/hunters_boots.png'],
    ['name' => 'Imperious Leggings', 'img' => 'img/imperious_leggings.png'],
    ['name' => 'Imported Trousers', 'img' => 'img/imported_trousers.png'],
    ['name' => 'Infantry Boots', 'img' => 'img/infantry_boots.png'],
    ['name' => 'Insolent Boots', 'img' => 'img/insolent_boots.png'],
    ['name' => 'Ironclad Leggings', 'img' => 'img/ironclad_leggings.png'],
    ['name' => 'Ivory King Boots', 'img' => 'img/ivory_king_boots.png'],
    ['name' => 'Jester`s Tights', 'img' => 'img/jesters_tights.png'],
    ['name' => 'Knight Leggings', 'img' => 'img/knight_leggings.png'],
    ['name' => 'Leydia Black Boots', 'img' => 'img/leydia_black_boots.png'],
    ['name' => 'Leydia White Boots', 'img' => 'img/leydia_white_boots.png'],
    ['name' => 'Lion Warrior Skirt', 'img' => 'img/lion_warrior_skirt.png'],
    ['name' => 'Looking Glass Leggings', 'img' => 'img/looking_glass_leggings.png'],
    ['name' => 'Loyce Leggings', 'img' => 'img/loyce_leggings.png'],
    ['name' => 'Lucatiel`s Trousers', 'img' => 'img/lucatiels_trousers.png'],
    ['name' => 'Mad Warrior Leggings', 'img' => 'img/mad_warrior_leggings.png'],
    ['name' => 'Manikin Boots', 'img' => 'img/manikin_boots.png'],
    ['name' => 'Mastodon Leggings', 'img' => 'img/mastodon_leggings.png'],
    ['name' => 'Minotaur Boots', 'img' => 'img/minotaur_boots.png'],
    ['name' => 'Mirrah Trousers', 'img' => 'img/mirrah_trousers.png'],
    ['name' => 'Moon Butterfly Skirt', 'img' => 'img/moon_butterfly_skirt.png'],
    ['name' => 'Nahr Alma Boots', 'img' => 'img/nahr_alma_boots.png'],
    ['name' => 'Necromancer Boots', 'img' => 'img/necromancer_boots.png'],
    ['name' => 'Old Bell Boots', 'img' => 'img/old_bell_boots.png'],
    ['name' => 'Old Knight Leggings', 'img' => 'img/old_knight_leggings.png'],
    ['name' => 'Old Mirrah Boots', 'img' => 'img/old_mirrah_boots.png'],
    ['name' => 'Old Sorcerer Boots', 'img' => 'img/old_sorcerer_boots.png'],
    ['name' => 'Old Soldier Leggings', 'img' => 'img/old_soldier_leggings.png'],
    ['name' => 'Old Sun Leggings', 'img' => 'img/old_sun_leggings.png'],
    ['name' => 'Old Ironclad Leggings', 'img' => 'img/old_ironclad_leggings.png'],
    ['name' => 'Peasant Trousers', 'img' => 'img/peasant_trousers.png'],
    ['name' => 'Penal Skirt', 'img' => 'img/penal_skirt.png'],
    ['name' => 'Prowler Leggings', 'img' => 'img/prowler_leggings.png'],
    ['name' => 'Rogue Leggings', 'img' => 'img/rogue_leggings.png'],
    ['name' => 'Royal Swordsman Leggings', 'img' => 'img/royal_swordsman_leggings.png'],
    ['name' => 'Saint`s Trousers', 'img' => 'img/saints_trousers.png'],
    ['name' => 'Sanctum Knight Leggings', 'img' => 'img/sanctum_knight_leggings.png'],
    ['name' => 'Sanctum Priestess Skirt', 'img' => 'img/sanctum_priestess_skirt.png'],
    ['name' => 'Shadow Leggings', 'img' => 'img/shadow_leggings.png'],
    ['name' => 'Shiva`s Leggings', 'img' => 'img/shivas_leggings.png'],
    ['name' => 'Soldier`s Leggings', 'img' => 'img/soldiers_leggings.png'],
    ['name' => 'Steel Leggings', 'img' => 'img/steel_leggings.png'],
    ['name' => 'Targray`s Leggings', 'img' => 'img/targrays_leggings.png'],
    ['name' => 'Tattered Cloth Manchettes', 'img' => 'img/tattered_cloth_manchettes.png'],
    ['name' => 'Throne Watcher Leggings', 'img' => 'img/throne_watcher_leggings.png'],
    ['name' => 'Throne Defender Leggings', 'img' => 'img/throne_defender_leggings.png'],
    ['name' => 'Traveling Merchant Boots', 'img' => 'img/traveling_merchant_boots.png'],
    ['name' => 'Varangian Leggings', 'img' => 'img/varangian_leggings.png'],
    ['name' => 'Velstadt`s Leggings', 'img' => 'img/velstadts_leggings.png'],
    ['name' => 'Vengarl`s Boots', 'img' => 'img/vengarls_boots.png'],
    ['name' => 'Wanderer Boots', 'img' => 'img/wanderer_boots.png'],
    ['name' => 'White Priest Boots', 'img' => 'img/white_priest_boots.png'],
    ['name' => 'White Hollow Mage Boots', 'img' => 'img/white_hollow_mage_boots.png'],
    ['name' => 'White Sorcerer Boots', 'img' => 'img/white_sorcerer_boots.png'],
    ['name' => 'Witchtree Branch Skirt', 'img' => 'img/witchtree_branch_skirt.png'],
    ['name' => 'Xanthous Waistcloth', 'img' => 'img/xanthous_waistcloth.png']
];

$tabItems = ['helms' => $helmsItems, 'chests' => $chestsItems, 'gloves' => $glovesItems, 'legs' => $legsItems];

echo json_encode($tabItems);
